BENCHMARK_ID=zephyr-f429zi
VARIANT_KIND=firmbench
BUILD_FAMILY=hoedur
DOCKER_IMAGE=docker.io/zephyrprojectrtos/ci@sha256:bc1bd27844ceb9661a1b7232980529a1a676dc10bacc613dd5fa8d859c986c7c
PLATFORM=linux/amd64
ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-0.16.1
CACHE_NAMESPACE=zephyr-f429zi
BASE_COMMIT=4256cd41df6c60f1832fd2deb14edc30ac7debab
REVERT_COMMITS=""
BOARD=nucleo_f429zi
SHIELD=x_nucleo_idb05a1
SAMPLE_DIR=samples/bluetooth/peripheral_dis
OVERLAY_CONFIG=bluetooth_hci.conf
PATCHES="bluetooth_hci_overlay.patch bt_hostonly_build.patch stm32f4_cap_flash_region_sizes.patch arm_generic_atomic.patch bt_hci_cmd_timeout.patch"
EARLY_RETURNS="arch_system_halt log_0 log_1 log_2 log_3 log_n printk shell_fprintf_fmt z_do_kernel_oops z_fatal_error z_impl_k_busy_wait z_impl_k_sleep z_tick_sleep z_vprintk"
OUTPUT_ELF=zephyr-bt-F429ZI.elf
REFERENCE_REL=../zephyr-bt-F429ZI.elf
