BENCHMARK_ID=Console
VARIANT_KIND=firmbench
BUILD_KIND=console
TOOLCHAIN=gcc6
BASE_IMAGE=ubuntu:20.04
CACHE_NAMESPACE=p2im-console-regular-riot-2018.04
CONTAINER_SOURCE=/home/bo/test/RIOT
UPSTREAM_URL=https://github.com/RIOT-OS/RIOT.git
BASE_COMMIT=99b170d8e8788edc49aa23248effbaeb1a1183d5
PATCHES="console-regular.patch"
RIOT_VERSION_OVERRIDE=2018.04-bo-desktop-HEAD
OUTPUT_ELF=Console.elf
OUTPUT_BIN=Console.bin
REFERENCE_REL=../Console.elf
