BENCHMARK_ID=zephyr-f429zi
VARIANT_KIND=x
BUILD_FAMILY=hoedur
DOCKER_IMAGE=docker.io/zephyrprojectrtos/ci@sha256:bc1bd27844ceb9661a1b7232980529a1a676dc10bacc613dd5fa8d859c986c7c
PLATFORM=linux/amd64
ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-0.16.1
CACHE_NAMESPACE=zephyr-f429zi
BASE_COMMIT=4256cd41df6c60f1832fd2deb14edc30ac7debab
REVERT_COMMITS=""
BOARD=nucleo_f429zi
SHIELD=x_nucleo_idb05a1
SAMPLE_DIR=samples/bluetooth/peripheral_dis
OVERLAY_CONFIG=bluetooth_hci.conf
PATCHES="bluetooth_hci_overlay.patch bt_hostonly_build.patch stm32f4_cap_flash_region_sizes.patch arm_generic_atomic.patch"
EARLY_RETURNS=""
OUTPUT_ELF=zephyrX.elf
REFERENCE_REL=../zephyrX.elf
