BENCHMARK_ID=riot-gnrc-networking-multifuzz
VARIANT_KIND=multifuzz
DOCKER_IMAGE=docker.io/riot/riotbuild@sha256:691413d2b0deb59dbd11d812de205f6f0c1898fc343551e83076b0b19e026422
PLATFORM=linux/amd64
CACHE_NAMESPACE=riot-multifuzz-2023.01
CONTAINER_REPO=/RIOT
BUILD_PROFILE=multifuzz-default
BASE_COMMIT=9142d9c37597c665fa704fe00ec8e377b35cf0d0
REVERT_COMMITS=""
BACKPORT_COMMITS=""
BOARD=stm32f3discovery
EXAMPLE_DIR=examples/gnrc_networking
APPLICATION=gnrc_networking
DISABLE_MODULES=cortexm_fpu
MAKE_JOBS=8
PATCHES=""
OUTPUT_ELF=gnrc_networking.elf
REFERENCE_REL=../gnrc_networking.elf
VERIFY_MODE=full
