BENCHMARK_ID=contiki-router
VARIANT_KIND=firmbench
DOCKER_IMAGE=docker.io/contiker/contiki-ng@sha256:0b6df3584cec7cc9991c0e3752ffc99863f044adf4405f231580083c8f1553ed
PLATFORM=linux/amd64
CACHE_NAMESPACE=contiki-v4.8
BASE_COMMIT=9771e9aaebbfbb5633ce69eb9876e0fc70bbcd6f
REVERT_COMMITS=""
BACKPORT_COMMITS=""
EXAMPLE=ip64-router
APPLICATION=ip64-router
TARGET=zoul
BUILD_SUBPATH=zoul/orion
PATCHES="cc2538_norom.patch cc2538_read.patch enc28j60_read.patch transparent_mac.patch ip64_sample.patch link_address_granularity.patch ipv6_checksums.patch 0001-ip64-dns64-add-bounds-checks-in-ip64_dns64_6to4.patch 0002-ip64-dns64-add-bounds-checks-in-ip64_dns64_4to6.patch"
OUTPUT_ELF=ip64-router.elf
REFERENCE_REL=../ip64-router.elf
EARLY_RETURNS="fade lpm_enter"
