BENCHMARK_ID=riot-gnrc-networking
VARIANT_KIND=firmbench
DOCKER_IMAGE=docker.io/riot/riotbuild@sha256:bd3a1e4d5bd7c930551aad2ec42e84b3a604acd1b2695232c915cd99c5e8c196
PLATFORM=linux/amd64
CACHE_NAMESPACE=riot-2022.07
BASE_COMMIT=68b89e77b3b8521fe614ca5100dde59ee831466a
REVERT_COMMITS=""
BACKPORT_COMMITS="b1dff296db8bff30caedf8db7a0d442ee6f0c922 269b3c97c23ac14bfcacfb8d83a83501ffd277de"
BOARD=cc2538dk
EXAMPLE_DIR=examples/gnrc_networking
APPLICATION=gnrc_networking
PATCHES="base.patch increase_stack_size.patch gnrc_networking_activate_modules.patch remove_checksums.patch prevent_null_deref_gnrc_sixlowpan_frag_sfr_arq_timeout.patch fix_CVE-2023-33973.patch fix_CVE-2023-33974.patch fix_CVE-2023-33975.patch"
OUTPUT_ELF=gnrc_networking.elf
REFERENCE_REL=../gnrc_networking.elf
