BENCHMARK_ID=zephyr-nrf
VARIANT_KIND=x
BUILD_FAMILY=fuzzware
DOCKER_IMAGE=docker.io/zephyrprojectrtos/zephyr-build@sha256:09d20690920a4ada89c08cccd6f555e4f48fbb00e9b0bf0462568071df96b55d
PLATFORM=linux/amd64
ZEPHYR_VERSION=2.2.0
CACHE_NAMESPACE=zephyr-2.2.0
BASE_COMMIT=e1dddf7befa7309bd2afc567b2e00d2e7362f7c4
REVERT_COMMITS=""
BOARD=nrf52840dk_nrf52840
SAMPLE_DIR=samples/bluetooth/peripheral_dis
PATCHES="fix-CVE-2020-10065.patch bt_hostonly_build.patch"
EARLY_RETURNS=""
OUTPUT_ELF=zephyr-CVE-2021-3329X.elf
REFERENCE_REL=../zephyr-CVE-2021-3329X.elf
