BENCHMARK_ID=zephyr-bt
VARIANT_KIND=firmbench
BUILD_FAMILY=fuzzware
DOCKER_IMAGE=docker.io/zephyrprojectrtos/zephyr-build@sha256:09d20690920a4ada89c08cccd6f555e4f48fbb00e9b0bf0462568071df96b55d
PLATFORM=linux/amd64
ZEPHYR_VERSION=2.2.0
CACHE_NAMESPACE=zephyr-2.2.0
BASE_COMMIT=e1dddf7befa7309bd2afc567b2e00d2e7362f7c4
REVERT_COMMITS="e1dddf7befa7309bd2afc567b2e00d2e7362f7c4"
BOARD=disco_l475_iot1
SAMPLE_DIR=samples/bluetooth/peripheral_dis
PATCHES=""
EARLY_RETURNS="arch_system_halt log_0 log_1 log_2 log_3 log_n printk shell_fprintf_fmt z_impl_k_busy_wait z_impl_k_sleep z_tick_sleep z_vprintk"
OUTPUT_ELF=zephyr-CVE-2020-10066.elf
REFERENCE_REL=../zephyr-CVE-2020-10066.elf
