BENCHMARK_ID=zephyr-sam4s
VARIANT_KIND=firmbench
BUILD_FAMILY=fuzzware
DOCKER_IMAGE=docker.io/zephyrprojectrtos/zephyr-build@sha256:09d20690920a4ada89c08cccd6f555e4f48fbb00e9b0bf0462568071df96b55d
PLATFORM=linux/amd64
ZEPHYR_VERSION=2.4.0
CACHE_NAMESPACE=zephyr-2.4.0
BASE_COMMIT=2a423bc6d37f916771bce65672efadf30e6ea74c
REVERT_COMMITS="2a423bc6d37f916771bce65672efadf30e6ea74c 6917d268482afc2da617a57456e1cdf4dd9c75d4 0ebd30000113f87a1f6090dd050974c1e540b42a 6f1ab93c66c59cf267bb2b974cf76a3b9b306e32"
BOARD=sam4s_xplained
SHIELD=atmel_rf2xx_xplained
SAMPLE_DIR=samples/net/sockets/echo_server
OVERLAY_CONFIG=overlay-802154.conf
EXTRA_DEFINES="-DCONFIG_SHELL=n -DCONFIG_NET_SHELL=n -DCONFIG_NET_L2_IEEE802154_SHELL=n -DCONFIG_NET_SHELL_DYN_CMD_COMPLETION=n"
PATCHES="ieee802154_rf2xx_size_check.patch wdt_sam_watchdog_callback_check.patch backport-CVE-2021-3321.patch"
EARLY_RETURNS="arch_system_halt log_0 log_1 log_2 log_3 log_n printk shell_fprintf_fmt z_impl_k_busy_wait z_impl_k_sleep z_tick_sleep z_vprintk"
OUTPUT_ELF=zephyr-CVE-2021-3322.elf
REFERENCE_REL=../zephyr-CVE-2021-3322.elf
